ci:1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: CI
 on:
   push:
     branches:
-      - main
+      - ci
       - 'release/**'
   pull_request:
     branches:
@@ -25,7 +25,9 @@ jobs:
 
     strategy:
       matrix:
-        os: [ubuntu-18.04, macos-12, windows-2019]
+        ##TODO
+        os: [ubuntu-18.04]
+#        os: [ubuntu-18.04, macos-12, windows-2019]
 
     steps:
       - uses: actions/setup-go@v2
@@ -154,7 +156,8 @@ jobs:
         with:
           go-version: ${{ env.GO_VERSION }}
       - uses: actions/checkout@v2
-      - run: |
+      - name: Install deps
+        run: |
           set -e -x
 
           packages="libbtrfs-dev"
@@ -197,7 +200,6 @@ jobs:
           if [ -n "${packages}" ]; then
             sudo apt-get update && sudo apt-get install -y ${packages}
           fi
-        name: Install deps
       - name: Build
         env:
           GOOS: ${{matrix.goos}}
@@ -218,7 +220,9 @@ jobs:
 
     strategy:
       matrix:
-        os: [ubuntu-18.04, macos-12, windows-2019, windows-2022]
+        ##TODO
+        os: [ubuntu-20.04]
+#        os: [ubuntu-18.04, macos-12, windows-2019, windows-2022]
         go-version: ['1.19', '1.18.5']
     steps:
       - uses: actions/setup-go@v2
@@ -244,142 +248,142 @@ jobs:
   #
   # Integration and CRI tests
   #
-  integration-windows:
-    name: Windows Integration
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 50
-    needs: [project, linters, protos, man]
-    env:
-      GOTEST: gotestsum --
-
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [windows-2019, windows-2022]
-        enable_cri_sandboxes: [ "", "sandboxed"]
-
-    defaults:
-      run:
-        shell: bash
-        working-directory: src/github.com/containerd/containerd
-
-    steps:
-      - uses: actions/setup-go@v2
-        with:
-          go-version: ${{ env.GO_VERSION }}
-
-      - uses: actions/checkout@v2
-        with:
-          path: src/github.com/containerd/containerd
-
-      - uses: actions/checkout@v2
-        with:
-          repository: kubernetes-sigs/cri-tools
-          path: src/github.com/kubernetes-sigs/cri-tools
-
-      - name: Set env
-        run: |
-          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
-          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
-          echo "${{ github.workspace }}/src/github.com/containerd/containerd/bin" >> $GITHUB_PATH
-          echo "${{ github.workspace }}/src/github.com/kubernetes-sigs/cri-tools/build/bin" >> $GITHUB_PATH
-
-      - run: script/setup/install-dev-tools
-
-      - name: Binaries
-        env:
-          CGO_ENABLED: 1
-        run: |
-          set -o xtrace
-          mingw32-make.exe binaries
-          cd ../../kubernetes-sigs/cri-tools
-          make critest
-
-      - run: script/setup/install-cni-windows
-
-      - env:
-          TEST_IMAGE_LIST: ${{github.workspace}}/repolist.toml
-          CRI_TEST_IMAGES: ${{github.workspace}}/cri-test-images.yaml
-          BUSYBOX_TESTING_IMAGE_REF: "k8s.gcr.io/e2e-test-images/busybox:1.29-2"
-          RESOURCE_CONSUMER_TESTING_IMAGE_REF: "k8s.gcr.io/e2e-test-images/resource-consumer:1.10"
-          WEBSERVER_TESTING_IMAGE_REF: "k8s.gcr.io/e2e-test-images/nginx:1.14-2"
-        run: |
-            cat > "${{ env.TEST_IMAGE_LIST }}" << EOF
-            busybox = "${{ env.BUSYBOX_TESTING_IMAGE_REF }}"
-            ResourceConsumer = "${{ env.RESOURCE_CONSUMER_TESTING_IMAGE_REF }}"
-            EOF
-            cat > "${{ env.CRI_TEST_IMAGES }}" << EOF
-            defaultTestContainerImage: ${{ env.BUSYBOX_TESTING_IMAGE_REF }}
-            webServerTestImage: ${{ env.WEBSERVER_TESTING_IMAGE_REF }}
-            EOF
-
-      - name: Get crictl tool
-        shell: powershell
-        run: |
-          # Get critctl tool. Used for cri-integration tests
-          $CRICTL_DOWNLOAD_URL="https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.21.0/crictl-v1.21.0-windows-amd64.tar.gz"
-          curl.exe -L $CRICTL_DOWNLOAD_URL -o c:\crictl.tar.gz
-          tar -xvf c:\crictl.tar.gz
-          mv crictl.exe "${{ github.workspace }}/bin/crictl.exe" # Move crictl somewhere in path
-
-      - run: script/setup/install-gotestsum
-      - name: Tests
-        env:
-          CGO_ENABLED: 1
-          GOTESTSUM_JUNITFILE: ${{github.workspace}}/test-unit-root.xml
-        run: mingw32-make.exe test root-test
-
-      - name: Integration 1
-        env:
-          CGO_ENABLED: 1
-          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
-          GOTESTSUM_JUNITFILE: ${{github.workspace}}/test-integration-serial-junit.xml
-        run: mingw32-make.exe integration
-
-      # Run the integration suite a second time. See discussion in github.com/containerd/containerd/pull/1759
-      - name: Integration 2
-        env:
-          TESTFLAGS_PARALLEL: 1
-          EXTRA_TESTFLAGS: "-short"
-          CGO_ENABLED: 1
-          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
-          GOTESTSUM_JUNITFILE: ${{github.workspace}}/test-integration-parallel-junit.xml
-        run: mingw32-make.exe integration
-
-      - name: CRI Integration Test
-        env:
-          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
-          TEST_IMAGE_LIST: ${{github.workspace}}/repolist.toml
-        run: |
-          make cri-integration
-
-      - name: cri-tools critest
-        env:
-          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
-          CRI_TEST_IMAGES: ${{github.workspace}}/cri-test-images.yaml
-        shell: powershell
-        run: |
-          Start-Process -FilePath containerd.exe -NoNewWindow -RedirectStandardError true -PassThru
-          get-process | sls containerd
-          start-sleep 5
-          # This test is exceedingly flaky only on ws2022 so skip for now to keep CI happy.
-          # Info: https://github.com/containerd/containerd/issues/6652
-          if( '${{ matrix.os }}' -eq 'windows-2022' )
-          {
-            $skip = "-ginkgo.skip=runtime should support exec with tty=true and stdin=true"
-          }
-          critest.exe --runtime-endpoint=npipe://.//pipe//containerd-containerd --test-images-file='${{env.CRI_TEST_IMAGES}}' --report-dir='${{github.workspace}}/critestreport' $skip
-
-      - uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: TestResults ${{ matrix.os }}
-          path: |
-            ${{github.workspace}}/*-junit.xml
+#  integration-windows:
+#    name: Windows Integration
+#    runs-on: ${{ matrix.os }}
+#    timeout-minutes: 50
+#    needs: [project, linters, protos, man]
+#    env:
+#      GOTEST: gotestsum --
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: [windows-2019, windows-2022]
+#        enable_cri_sandboxes: [ "", "sandboxed"]
+#
+#    defaults:
+#      run:
+#        shell: bash
+#        working-directory: src/github.com/containerd/containerd
+#
+#    steps:
+#      - uses: actions/setup-go@v2
+#        with:
+#          go-version: ${{ env.GO_VERSION }}
+#
+#      - uses: actions/checkout@v2
+#        with:
+#          path: src/github.com/containerd/containerd
+#
+#      - uses: actions/checkout@v2
+#        with:
+#          repository: kubernetes-sigs/cri-tools
+#          path: src/github.com/kubernetes-sigs/cri-tools
+#
+#      - name: Set env
+#        run: |
+#          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
+#          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
+#          echo "${{ github.workspace }}/src/github.com/containerd/containerd/bin" >> $GITHUB_PATH
+#          echo "${{ github.workspace }}/src/github.com/kubernetes-sigs/cri-tools/build/bin" >> $GITHUB_PATH
+#
+#      - run: script/setup/install-dev-tools
+#
+#      - name: Binaries
+#        env:
+#          CGO_ENABLED: 1
+#        run: |
+#          set -o xtrace
+#          mingw32-make.exe binaries
+#          cd ../../kubernetes-sigs/cri-tools
+#          make critest
+#
+#      - run: script/setup/install-cni-windows
+#
+#      - env:
+#          TEST_IMAGE_LIST: ${{github.workspace}}/repolist.toml
+#          CRI_TEST_IMAGES: ${{github.workspace}}/cri-test-images.yaml
+#          BUSYBOX_TESTING_IMAGE_REF: "k8s.gcr.io/e2e-test-images/busybox:1.29-2"
+#          RESOURCE_CONSUMER_TESTING_IMAGE_REF: "k8s.gcr.io/e2e-test-images/resource-consumer:1.10"
+#          WEBSERVER_TESTING_IMAGE_REF: "k8s.gcr.io/e2e-test-images/nginx:1.14-2"
+#        run: |
+#            cat > "${{ env.TEST_IMAGE_LIST }}" << EOF
+#            busybox = "${{ env.BUSYBOX_TESTING_IMAGE_REF }}"
+#            ResourceConsumer = "${{ env.RESOURCE_CONSUMER_TESTING_IMAGE_REF }}"
+#            EOF
+#            cat > "${{ env.CRI_TEST_IMAGES }}" << EOF
+#            defaultTestContainerImage: ${{ env.BUSYBOX_TESTING_IMAGE_REF }}
+#            webServerTestImage: ${{ env.WEBSERVER_TESTING_IMAGE_REF }}
+#            EOF
+#
+#      - name: Get crictl tool
+#        shell: powershell
+#        run: |
+#          # Get critctl tool. Used for cri-integration tests
+#          $CRICTL_DOWNLOAD_URL="https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.21.0/crictl-v1.21.0-windows-amd64.tar.gz"
+#          curl.exe -L $CRICTL_DOWNLOAD_URL -o c:\crictl.tar.gz
+#          tar -xvf c:\crictl.tar.gz
+#          mv crictl.exe "${{ github.workspace }}/bin/crictl.exe" # Move crictl somewhere in path
+#
+#      - run: script/setup/install-gotestsum
+#      - name: Tests
+#        env:
+#          CGO_ENABLED: 1
+#          GOTESTSUM_JUNITFILE: ${{github.workspace}}/test-unit-root.xml
+#        run: mingw32-make.exe test root-test
+#
+#      - name: Integration 1
+#        env:
+#          CGO_ENABLED: 1
+#          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
+#          GOTESTSUM_JUNITFILE: ${{github.workspace}}/test-integration-serial-junit.xml
+#        run: mingw32-make.exe integration
+#
+#      # Run the integration suite a second time. See discussion in github.com/containerd/containerd/pull/1759
+#      - name: Integration 2
+#        env:
+#          TESTFLAGS_PARALLEL: 1
+#          EXTRA_TESTFLAGS: "-short"
+#          CGO_ENABLED: 1
+#          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
+#          GOTESTSUM_JUNITFILE: ${{github.workspace}}/test-integration-parallel-junit.xml
+#        run: mingw32-make.exe integration
+#
+#      - name: CRI Integration Test
+#        env:
+#          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
+#          TEST_IMAGE_LIST: ${{github.workspace}}/repolist.toml
+#        run: |
+#          make cri-integration
+#
+#      - name: cri-tools critest
+#        env:
+#          ENABLE_CRI_SANDBOXES: ${{ matrix.enable_cri_sandboxes }}
+#          CRI_TEST_IMAGES: ${{github.workspace}}/cri-test-images.yaml
+#        shell: powershell
+#        run: |
+#          Start-Process -FilePath containerd.exe -NoNewWindow -RedirectStandardError true -PassThru
+#          get-process | sls containerd
+#          start-sleep 5
+#          # This test is exceedingly flaky only on ws2022 so skip for now to keep CI happy.
+#          # Info: https://github.com/containerd/containerd/issues/6652
+#          if( '${{ matrix.os }}' -eq 'windows-2022' )
+#          {
+#            $skip = "-ginkgo.skip=runtime should support exec with tty=true and stdin=true"
+#          }
+#          critest.exe --runtime-endpoint=npipe://.//pipe//containerd-containerd --test-images-file='${{env.CRI_TEST_IMAGES}}' --report-dir='${{github.workspace}}/critestreport' $skip
+#
+#      - uses: actions/upload-artifact@v2
+#        if: always()
+#        with:
+#          name: TestResults ${{ matrix.os }}
+#          path: |
+#            ${{github.workspace}}/*-junit.xml
 
   integration-linux:
     name: Linux Integration
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-20.04
     timeout-minutes: 40
     needs: [project, linters, protos, man]
 
@@ -404,6 +408,51 @@ jobs:
 
       - uses: actions/checkout@v2
 
+      - name: Install deps
+        run: |
+          set -e -x
+
+          packages="libbtrfs-dev"
+          platform="${{matrix.goos}}/${{matrix.goarch}}"
+          if [ -n "${{matrix.goarm}}" ]; then
+            platform+="/v${{matrix.goarm}}"
+          fi
+
+          case "${platform}" in
+          linux/arm/v5)
+            packages+=" crossbuild-essential-armel"
+            echo "CGO_ENABLED=1" >> $GITHUB_ENV
+            echo "CC=arm-linux-gnueabi-gcc" >> $GITHUB_ENV
+            ;;
+          linux/arm/v7)
+            packages+=" crossbuild-essential-armhf"
+            echo "CGO_ENABLED=1" >> $GITHUB_ENV
+            echo "CC=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
+            ;;
+          linux/arm64)
+            packages+=" crossbuild-essential-arm64"
+            echo "CGO_ENABLED=1" >> $GITHUB_ENV
+            echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
+            ;;
+          linux/ppc64le)
+            packages+=" crossbuild-essential-ppc64el"
+            echo "CGO_ENABLED=1" >> $GITHUB_ENV
+            echo "CC=powerpc64le-linux-gnu-gcc" >> $GITHUB_ENV
+            ;;
+          linux/riscv64)
+            packages+=" crossbuild-essential-riscv64"
+            echo "CGO_ENABLED=1" >> $GITHUB_ENV
+            echo "CC=riscv64-linux-gnu-gcc" >> $GITHUB_ENV
+            ;;
+          windows/arm/v7)
+            echo "CGO_ENABLED=0" >> $GITHUB_ENV
+            ;;
+          esac
+
+          if [ -n "${packages}" ]; then
+            sudo apt-get update && sudo apt-get install -y ${packages}
+          fi
+
       - name: Install containerd dependencies
         env:
           RUNC_FLAVOR: ${{ matrix.runc }}
@@ -414,6 +463,7 @@ jobs:
           script/setup/install-cni $(grep containernetworking/plugins go.mod | awk '{print $2}')
           script/setup/install-critools
           script/setup/install-failpoint-binaries
+          
 
       - name: Install criu
         run: |
@@ -512,27 +562,27 @@ jobs:
             *-junit.xml
             ${{github.workspace}}/critestreport/*.xml
 
-  tests-mac-os:
-    name: MacOS unit tests
-    runs-on: macos-12
-    timeout-minutes: 10
-    needs: [project, linters, protos, man]
-    env:
-      GOTEST: gotestsum --
-
-    steps:
-      - uses: actions/setup-go@v2
-        with:
-          go-version: ${{ env.GO_VERSION }}
-      - uses: actions/checkout@v2
-      - run: script/setup/install-gotestsum
-      - name: Tests
-        env:
-          GOTESTSUM_JUNITFILE: "${{ github.workspace }}/macos-test-junit.xml"
-        run: make test
-      - uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: TestResults MacOS
-          path: |
-            *-junit.xml
+#  tests-mac-os:
+#    name: MacOS unit tests
+#    runs-on: macos-12
+#    timeout-minutes: 10
+#    needs: [project, linters, protos, man]
+#    env:
+#      GOTEST: gotestsum --
+#
+#    steps:
+#      - uses: actions/setup-go@v2
+#        with:
+#          go-version: ${{ env.GO_VERSION }}
+#      - uses: actions/checkout@v2
+#      - run: script/setup/install-gotestsum
+#      - name: Tests
+#        env:
+#          GOTESTSUM_JUNITFILE: "${{ github.workspace }}/macos-test-junit.xml"
+#        run: make test
+#      - uses: actions/upload-artifact@v2
+#        if: always()
+#        with:
+#          name: TestResults MacOS
+#          path: |
+#            *-junit.xml
